api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('bbs/<int:pk>/comments/', views.comments),
    path('bbs/<int:pk>/', views.BbDetailView.as_view()),
    path('bbs/', views.bbs),
]

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'main'
urlpatterns = [
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/', views.MainPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MainPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/register/activate/<str:sign>/', views.user_activate, name='register_activate'),
    path('accounts/register/done/', views.RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', views.RegisterUserView.as_view(), name='register'),
    path('accounts/profile/change/<int:pk>/', views.profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', views.profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/change/', views.ChangeUserInfoView.as_view(), name='profile_change'),
    path('account/profile/delete/', views.DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/add/', views.profile_bb_add, name='profile_bb_add'),
    path('account/profile/<int:pk>/', views.profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/password/change/', views.MainPasswordChangeView.as_view(), name='password_change'),
    path('accounts/logout/', views.MainLogoutView.as_view(), name='logout'),
    path('accounts/login/', views.MainLoginView.as_view(), name='login'),
    path('bbs/', views.bb_list, name='bb_list'),
    path('<int:rubric_pk>/<int:pk>/', views.bb_detail, name='bb_detail'),
    path('<int:pk>/', views.by_rubric, name='by_rubric'),
    path('', views.index, name='index'),
]
urlpatterns += [
    path('<str:page>/', views.other_page, name='other'),
]

myboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse
from django.dispatch import Signal
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

from .utilities import send_activation_notification, get_timestamp_path, send_new_comment_notification


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True,
                                       db_index=True,
                                       verbose_name='passed activation?')
    send_messages = models.BooleanField(default=True,
                                        verbose_name='Send notification of new comments?')

    class Meta(AbstractUser.Meta):
        pass

    def delete(self, *args, **kwargs):
        for bb in self.bb_set.all():
            bb.delete()
        super().delete(*args, *kwargs)


user_registrated = Signal(providing_args=['instance'])


def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])


user_registrated.connect(user_registrated_dispatcher)


class Rubric(models.Model):
    name = models.CharField(
        max_length=20,
        db_index=True,
        unique=True,
        verbose_name='Название',
    )
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Order')
    super_rubric = models.ForeignKey('SuperRubric', on_delete=models.PROTECT,
                                     null=True, blank=True, verbose_name='Above category')

    def __str__(self):
        return self.name


class SuperRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=True)


class SuperRubric(Rubric):
    objects = SuperRubricManager()

    class Meta:
        proxy = True
        ordering = ('order', 'name', )
        verbose_name = 'Above category'
        verbose_name_plural = 'Above categories'

    def __str__(self):
        return self.name


class SubRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=False)


class SubRubric(Rubric):
    objects = SubRubricManager()

    def __str__(self):
        return f'{self.super_rubric.name} - {self.name}'

    class Meta:
        proxy = True
        ordering = ('super_rubric__order', 'super_rubric__name', 'order', 'name')
        verbose_name = 'Subheading'
        verbose_name_plural = 'Subheadings'


class Bb(models.Model):
    rubric = models.ForeignKey(SubRubric,
                               null=True,
                               on_delete=models.PROTECT,
                               verbose_name='category',
                               related_name='bbs')
    title = models.CharField(max_length=40, verbose_name='product', )
    content = models.TextField(verbose_name='description')
    price = models.FloatField(default=0, verbose_name='price', )
    contacts = models.TextField(verbose_name='Contacts')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='picture')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='the author of the ad')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='display in the list?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='published by')

    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name = 'ad'
        verbose_name_plural = 'ads'
        ordering = ['-created_at', ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:bb_detail', args=[self.rubric.pk, self.pk, ])


class AdditionalImage(models.Model):
    bb = models.ForeignKey(Bb, on_delete=models.CASCADE, verbose_name='ad')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='picture')

    class Meta:
        verbose_name = 'additional illustration'
        verbose_name_plural = 'additional illustrations'


class Comment(models.Model):
    bb = models.ForeignKey(Bb, on_delete=models.CASCADE, verbose_name='ad')
    author = models.CharField(max_length=30, verbose_name='author')
    content = models.TextField(verbose_name='the contents')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Output to the screen?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='published')

    class Meta:
        verbose_name_plural = 'comments'
        verbose_name = 'comment'
        ordering = ['created_at']


def post_save_dispatcher(sender, **kwargs):
    author = kwargs['instance'].bb.author
    if kwargs['created'] and author.send_messages:
        send_new_comment_notification(kwargs['instance'])


post_save.connect(post_save_dispatcher, sender=Comment)

main/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetConfirmView, \
    PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.exceptions import TemplateDoesNotExist
from django.template.loader import get_template
from django.views.generic import UpdateView, TemplateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.signing import BadSignature
from django.core.paginator import Paginator
from django.db.models import Q

from .utilities import signer

from .models import AdvUser, SubRubric, Bb, Comment
from .forms import ChangeUserInfoForm, RegisterUserForm, SearchForm, BbForm, AIFormSet, UserCommentForm, \
    GuestCommentForm

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView


def index(request):
    bbs = Bb.objects.filter(is_active=True)[:5]
    context = {
        'bbs': bbs,
    }
    return render(request, 'main/index.html', context)


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'User\'s personal data has been successfully changed'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class MainLoginView(LoginView):
    template_name = 'main/login.html'


class MainLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


@login_required
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)
    context = {
        'bbs': bbs,
    }
    return render(request, 'main/profile.html', context)


@login_required
def profile_bb_add(request):
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS,
                                     'Объявление добавлено')
                return redirect('main:profile')
    else:
        form = BbForm(initial={'author': request.user.pk})
        formset = AIFormSet()
        context = {
            'form': form,
            'formset': formset,
        }
        return render(request, 'main/profile_bb_add.html', context)


class MainPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'The user\'s password has been successfully changed'


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'The user is deleted')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


def bb_list(request):
    bbs = Bb.objects.order_by('-created_at')
    context = {
        'bbs': bbs,
    }
    return render(request, 'main/bb_list.html', context)


def bb_detail(request, rubric_pk, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()
    comments = Comment.objects.filter(bb=pk, is_active=True)
    initial = {'bb': bb.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Comment added')
        else:
            form = c_form
            messages.add_message(request, messages.WARNING,
                                 'The comment is not added')
    context = {
        'bb': bb,
        'ais': ais,
        'comments': comments,
        'form': form,
    }
    return render(request, 'main/bb_detail.html', context)


def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {
        'rubric': rubric,
        'page': page,
        'bbs': page.object_list,
        'form': form,
        'bb_rubric_list': bbs,
    }
    return render(request, 'main/by_rubric.html', context)


@login_required
def profile_bb_detail(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()
    context = {
        'bb': bb,
        'ais': ais,
    }
    return render(request, 'main/profile_bb_detail.html', context)


@login_required
def profile_bb_change(request, pk):
    bb = get_object_or_404(Bb, pk=pk, author=request.user)
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Ad fixed')
                return redirect('main:profile')
    else:
        form = BbForm(instance=bb)
        formset = AIFormSet(instance=bb)
        context = {
            'form': form,
            'formset': formset,
            'bb': bb,
        }
        return render(request, 'main/profile_bb_change.html', context)


@login_required
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk, author=request.user)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request, messages.SUCCESS, 'Ad removed')
        return redirect('main:profile')
    else:
        context = {
            'bb': bb,
        }
        return render(request, 'main/profile_bb_delete.html', context)


class MainPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('main:password_reset_complete')


class MainPasswordResetView(PasswordResetView):
    success_url = reverse_lazy('main:password_reset_done')


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

main/templates/main/bad_signature.html
{% extends 'base.html' %}
{% block title %}Error when activating{% endblock %}

{% block content %}
    <h2>Activation error</h2>
    <p>Activation of a user with this name failed!</p>
    <p><a href="{% url 'main:register' %}">Register again</a></p>
{% endblock %}

main/templates/main/bb_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load thumbnail %}
{% block title %}{{ bb.title }}{% endblock %}
{% block content %}

    <div class="card-body">
    <h4>User ad <span style="color: orangered; font-style: italic">{{ bb.author.first_name }}</span> <sup style="font-style: italic; color: royalblue">
            <a href="{% url 'main:by_rubric' bb.rubric.pk %}">Category {{ bb.rubric }}</a>
        </sup></h4>
    <hr>
    <h4 style="text-align: center" class="card-title">{{ bb.title }} <sup><span style="color: orangered;
            font-style: italic; font-size: 11px;">
                Date of publication: {{ bb.created_at|date:"d.m.Y H:i:s" }}</span></sup></h4>
    {% if bb.image %}
    <img style="width: 150px" class="mr-3" src="{% thumbnail bb.image 'default' %}" alt="">
    {% endif %}
    {% if ais %}
    {% for ai in ais %}
        <img style="width: 150px" class="mr-3" src="{% thumbnail ai.image 'default' %}" alt="">
    {% endfor %}
{% endif %}
    <p style="font-style: italic" class="card-text">{{ bb.content }}</p>
      {% if bb.price %}
      <p class="card-link">Price {{ bb.price }} rub</p>
      {% else %}
      <p class="card-link">Price 0 руб</p>
      {% endif %}
    <hr>
    <p><a href="{% url 'main:by_rubric' pk=bb.rubric.pk %}{{ all }}">Back</a></p>
    <hr>
    <h6>Comments on the ad:</h6>
        <hr>
        {% if comments %}
<div class="mt-5">
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>Comment from: <span style="color: orangered; font-style: italic">{{ comment.author }}</span></h5>
        <hr>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
            {% else %}
            <p>No comments...</p>
{% endif %}
    <hr>
    <h6 style="text-align: center">Add a comment</h6>
        <hr>
        <form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
    <hr>
  </div>
{% endblock %}

main/templates/main/bb_list.html
{% extends 'base.html' %}
{% load bb_tags %}
{% block title %}List of ads{% endblock %}
{% block content %}
    <h4>All ads <sup>{% total_bb %}</sup></h4>
    <hr>
    {% for bb in bbs %}
            <div style="margin-bottom: 20px; box-shadow: 3px 3px 15px black" class="card">
  <div class="card-body">
    <h4 class="card-title"><a href="{{ bb.get_absolute_url }}">{{ bb.title }}</a></h4>
      <hr>
  {% if bb.image %}
    <img style="width: 150px" src="{{ bb.image.url }}" alt="">
        {% else %}
        <p>The user did not add any images</p>
    {% endif %}
      <p class="card-link"><span style="color: orangered;
            font-style: italic; font-size: 11px;">
                {{ bb.created_at|date:"d.m.Y H:i:s" }}</span></p>
    <p style="font-style: italic" class="card-text">{{ bb.content|truncatewords:10 }}</p>
      <hr>
      {% if bb.price %}
      <p class="card-link">Price {{ bb.price }} rub</p>
      {% else %}
      <p class="card-link">Price 0 rub</p>
      {% endif %}
      <hr>
      <a style="box-shadow: 3px 3px 5px black"
         href="{{ bb.get_absolute_url }}"
         type="button" class="btn btn-primary">More detailed</a>
  </div>
</div>
        {% endfor %}
{% endblock %}

main/templates/main/by_rubric.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}
{% load bb_tags %}
{% block title %}Ads in the section {{ rubric }}{% endblock %}
{% block content %}
        <h4>Ads in the section <span style="font-style: italic;">"{{ rubric }}"</span></h4>
    <hr>
        <form style="width: 100%">
            {% bootstrap_form form show_label=False %}
            <input type="submit" value="Искать" class="btn btn-primary" style="width: 100%">
        </form>
    <hr>
{% if bbs %}
    {% for bb in bbs %}
            <div style="margin-bottom: 20px; box-shadow: 3px 3px 15px black" class="card">
  <div class="card-body">
    <h4 class="card-title"><a href="{{ bb.get_absolute_url }}">{{ bb.title }}</a></h4>
      <hr>
  {% if bb.image %}
    <img style="width: 150px" class="mr-3" src="{% thumbnail bb.image 'default' %}" alt="">
        {% else %}
        <p>The user did not add any images</p>
    {% endif %}
      <p class="card-link"><span style="color: orangered;
            font-style: italic; font-size: 11px;">
                {{ bb.created_at|date:"d.m.Y H:i:s" }}</span></p>
    <p style="font-style: italic" class="card-text">{{ bb.content|truncatewords:10 }}</p>
      <hr>
      {% if bb.price %}
      <p class="card-link">Price {{ bb.price }} rub</p>
      {% else %}
      <p class="card-link">Price 0 rub</p>
      {% endif %}
      <hr>
      <a style="box-shadow: 3px 3px 5px black" href="{{ bb.get_absolute_url }}" type="button" class="btn btn-primary">More detailed</a>
  </div>
</div>
        {% endfor %}
    <hr>
{% bootstrap_pagination page url=keyword %}
{% endif %}
    
{% endblock %}

main/templates/main/change_user_info.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Editing personal data{% endblock %}
{% block content %}
    <h2>Editing the user's personal data {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Save' %}{% endbuttons %}
    </form>
    <hr>
    <p><a href="{% url 'main:password_change' %}">Change your password</a></p>
    <hr>
    <p><a style="color: darkred" href="{% url 'main:profile_delete' %}">Delete an account</a></p>
{% endblock %}

main/templates/main/delete_user.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Deleting a user{% endblock %}
{% block content %}
    <h2>Deleting a user {{ user.username }}</h2>
    <p>Are you sure you want to delete your account permanently?
        All information will be lost!</p>
    <p>After deleting it, you will not be able to restore your account!</p>
    <form method="post">
        {% csrf_token %}
        {% buttons submit="Удалить" %}{% endbuttons %}
    </form>
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load crispy_forms_filters %}
{% load bb_tags %}
{% block title %}Main{% endblock %}
{% block content %}
    <div style="text-align: center; color: dodgerblue">
        <h1>Bulletin board</h1>
      <p>Welcome to the free Bulletin Board website</p>
    <hr>
    </div>

    {% for bb in bbs %}
            <div style="margin-bottom: 20px; box-shadow: 3px 3px 15px black" class="card">
  <div class="card-body">
    <h4 class="card-title">{{ bb.title }}</h4>
      <hr>
  {% if bb.image %}
    <img style="width: 150px" class="mr-3" src="{% thumbnail bb.image 'default' %}" alt="">
        {% else %}
        <p>The user did not add any images</p>
    {% endif %}
      <p class="card-link"><span style="color: orangered;
            font-style: italic; font-size: 11px;">
                {{ bb.created_at|date:"d.m.Y H:i:s" }}</span></p>
    <p style="font-style: italic" class="card-text">{{ bb.content|truncatewords:10 }}</p>
      <hr>
      {% if bb.price %}
      <p class="card-link">Price {{ bb.price }} rub</p>
      {% else %}
      <p class="card-link">Price 0 rub</p>
      {% endif %}
      <hr>
      <a style="box-shadow: 3px 3px 5px black" href="{{ bb.get_absolute_url }}" type="button" class="btn btn-primary">More detailed</a>
  </div>
</div>
        {% endfor %}
{% endblock %}

main/templates/main/logout.html
{% extends 'base.html' %}
{% block title %}Logout{% endblock %}

{% block content %}
    <h2>Logout</h2>
    <p>You have successfully logged out of the site</p>
{% endblock %}

main/templates/main/new_bb.html
<ol>
        {% for bb in bbs  %}
            <li><a href="#">{{ bb.title }}</a>
            <sup><span style="color: orangered;
            font-style: italic; font-size: 11px;">
                {{ bb.published|date:"d.m.Y H:i:s" }}</span></sup>
            </li>
        {% endfor %}
    </ol>

main/templates/main/profile.html
{% extends 'base.html' %}
{% load bb_tags %}
{% load static %}
{% load thumbnail %}

{% block title %}User profile{% endblock %}

{% block content %}
<h2>User profile {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Hello, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Hello!</p>
{% endif %}
    <hr>
    {% if bbs %}
<h3><a href="{% url 'main:profile_bb_add' %}">Create a new one ad </a><sup>
    <span class="badge badge-primary">{% total_user_bb user %}</span></sup></h3>
    <hr>
    {% for bb in bbs %}
            <div style="margin-bottom: 20px; box-shadow: 3px 3px 15px black" class="card">
  <div class="card-body">
    <h4 class="card-title">{{ bb.title }}</h4>
      <hr>
  {% if bb.image %}
    <img style="width: 150px" src="{{ bb.image.url }}" alt="">
        {% else %}
        <p>The user did not add any images</p>
    {% endif %}
      <p class="card-link"><span style="color: orangered;
            font-style: italic; font-size: 11px;">
                {{ bb.created_at|date:"d.m.Y H:i:s" }}</span></p>
    <p style="font-style: italic" class="card-text">{{ bb.content|truncatewords:10 }}</p>
      <hr>
      {% if bb.price %}
      <p class="card-link">Price {{ bb.price }} rub</p>
      {% else %}
      <p class="card-link">Price 0 rub</p>
      {% endif %}
      <hr>
  <p style="font-style: italic">Comments <sup style="color: red">{{ bb.comment_set.count }}</sup></p>
      <hr>
  <a href="{% url 'main:profile_bb_change' pk=bb.pk%}">Edit</a>
      <hr>
      <a href="{% url 'main:profile_bb_delete' pk=bb.pk%}">Delete</a>
  </div>
</div>
        {% endfor %}
{% endif %}
{% endblock %}

main/templates/main/profile_bb_change.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}Edit an ad{% endblock %}

{% block content %}
<h2>Edit an ad {{ bb.title }}, the user {{ bb.author }}</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_formset formset layout='horizontal' %}
    {% buttons submit='Save' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile_bb_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load thumbnail %}

{% block title %}Deleting an ad - user Profile{% endblock %}

{% block content %}
<h2>Deleting an ad</h2>
<div class="container-fluid mt-3">
    <div class="row">
        {% if bb.image %}
        <div class="col-md-auto">
            <img style="width: 150px" class="mr-3" src="{% thumbnail bb.image 'default' %}" alt="">
        </div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p class="font-weight-bold">{{ bb.price }} руб.</p>
            <p>{{ bb.contacts }}</p>
            <p class="font-italic">The announcement added {{ bb.created_at }}</p>
        </div>
    </div>
</div>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-primary" type="submit" value="Delete">
</form>
{% endblock %}

main/templates/main/register_done.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Registration is completed{% endblock %}
{% block content %}
    <h2>Registration</h2>
    <p>User registration is completed.</p>
    <p>To the email address,
        specified by the user, an activation email has been sent.</p>
{% endblock %}

main/templates/main/register_user.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Registration{% endblock %}
{% block content %}
    <h2>Registering a new user</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Register' %}{% endbuttons %}
    </form>
{% endblock %}